# "moved" to keyboard.json:
#MCU = atmega32u4
#PIN_COMPATIBLE=elite_c
#BOOTLOADER = atmel-dfu
#MOUSEKEY_ENABLE = yes

CAPS_WORD_ENABLE = yes
LTO_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
SPLIT_KEYBOARD = yes
#TRI_LAYER_ENABLE = yes
MOUSEKEY_ENABLE = yes
TAP_DANCE_ENABLE = yes
#CONSOLE_ENABLE = yes

